server:
  port: 12080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:13080/eureka/
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    account:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/zeongit_account?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      username: root
      password: ASDasd+-*/00
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
  main:
    allow-bean-definition-overriding: true
account:
  registerVerificationCodePrefix: register_verification_code:%s
  forgetVerificationCodePrefix: forget_verification_code:%s
  verificationCodeTimeout: 300000
  jwtExpiresSecond: 5184000000
  updatePasswordTimePrefix: base:update_password_time:%s
qiniu:
  qiniuAccessKey: 0G397Ly7Z6pqnm2MPUhHIbMFzvBX19yyhu-RdiqI
  qiniuSecretKey: _xLtVKJ4VNUrwSsEGkJBHtV2s6mZ2QG2yDXaCvTk
  qiniuHost: rs.qiniu.com
  qiniuTemporaryBucket: temporary
  qiniuAvatarBucket: head
  qiniuBackgroundBucket: background
  qiniuTemporaryBucketUrl: http://temporary.zeongit.cn
  qiniuAvatarBucketUrl: http://avatar.zeongit.cn
  qiniuBackgroundBucketUrl: http://background.zeongit.cn
